### ISSUE TITLE
can't get this to work

### ISSUE THREAD

**Issue by cpup22** [QuadDepo/kickstarter-data#2]
the url, it is a full kickstarter url like this: https://www.kickstarter.com/projects/lisadeluca/internet-of-mysterious-things-iomt

I can't get the example code to work. ex:

```
var options = {
            url: "https://www.kickstarter.com/projects/lisadeluca/internet-of-mysterious-things-iomt"
        }
        var project = new KS.project(options);
        project.pledged().timeLeft().request(function(err, data){
            console.log("************** in the kickstarter response");
            console.log(err);
            console.log(data);
        });
```

**Comment by mcwhittemore** [comment]
@cpup22 - I'm so sorry to have seen this just now. I need to add a noticed to this project to say its inactive. KS has changed the html of their site a few too many times for this to still work.

Also, can I assume this KS project is yours? I'm really sad I missed it by not seeing this until now. We just had our first child and this sounds like a great book.

**Comment by cpup22** [comment]
@mcwhittemore its on ifundwomen.com still! 😀 Congrats on baby #1
