### ISSUE TITLE
It this still working?

### ISSUE THREAD

**Issue by QuadDepo** [QuadDepo/kickstarter-data#3]
Hey there,

i was interested in using this my website.

Some endpoints are working but the backers, plegdeGoal aren't.

And i was wondering if this still a thing i can build apon?

**Comment by mcwhittemore** [comment]
I haven't used this in awhile, but if you want, I can transfer ownership to you.

**Comment by QuadDepo** [comment]
Sure, i will take a look at it. Its never bad to have a little side project :-)

**Comment by mcwhittemore** [comment]
Because you have a fork I can't transfer this to you, so I added you as a collaborator. If you'd prefer it was transferred, just say the word.

**Comment by QuadDepo** [comment]
i deleted my fork.

**Comment by QuadDepo** [comment]
Not sure what you want, i dont really care. Would love to work on this project anyways

**Comment by mcwhittemore** [comment]
I just transferred it to you. Have fun, make something cool!

**Comment by QuadDepo** [comment]
Thanks i will 👍
